"""empty message

Revision ID: 985b739b11dd
Revises: 5aba92f36a47
Create Date: 2025-03-06 19:19:06.171630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985b739b11dd'
down_revision = '5aba92f36a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
